name: UbuntuBuild

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install prerequisites
      run: ./scripts/InstallPrerequisites-Ubuntu.sh
    - name: Build
      run: 
        mkdir shasta-build
        cd shasta-build 
        cmake ..
        make -j all
        make install


